functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
  - Страница магазина не перезагружается
  - Корзина товаров сохраняется в течение сессии барузера
  - На странице товара и в каталоге выводятся название, рейтинг, цена со скидкой и без.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
  - Сайт должен иметь мобильную версию.
implicit:
  - Корректная локализация(смена языка)
  - Корректное суммирование корзины
  - Корректный подтсчет процента скидки
 
